_commit: v0.2.0
_src_path: https://github.com/gabriel-andreescu/BethesdaModKit.git
author: GabonZ
bmk_repository: https://github.com/gabriel-andreescu/BethesdaModKit.git
clib_util: false
components:
  - native
description: Fixes music left in the playback queue after loading a save.
devbench_api: true
devbench_tests: true
game: skyrim
native_settings: false
native_source: src
pack_assets: false
pre_commit: true
project_name: MusicQueueFix
